name: Actions
run-name: Group water learning GitHub Actions .
on: [push]
jobs:
  cicd-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Run ESLint
        run: |
          ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx

      - name: Start MongoDB
        uses: MongoCamp/mongodb-github-action@1.0.0
        with:
          mongodb-version: 5.0

      - name: Start test server
        run: |
             npm run start:test &
             npm test

      # # deploy to s3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region: eu-west-2

      - name: Create zip file
        run: zip -r water-acebook.zip . -x '*.git*' -x "*node_modules/*" -x "*cypress/*" -x "*cypress.config*" -x "*jest.config*"

      - name: Upload Artifact to s3
        run: aws s3 cp water-acebook.zip s3://water-acebook-bucket/water-acebook.zip

      - name: CodeDeploy
        run: aws deploy create-deployment --application-name AceBook-Water-App --deployment-group-name production --s3-location bucket=water-acebook-bucket,bundleType=zip,key=water-acebook.zip
