name: Actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
