name: Actions
run-name: Group water learning GitHub Actions
on: [push]
jobs:
  cicd-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Run ESLint
        run: |
          ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx

      - name: Start test server
        run: npm run start:test

      - name: Run tests
        run: npm test

      # add uses mongodb mongodb-community@5.0
      # start db
      - name: Start MongoDB
        uses: MongoCamp/mongodb-github-action@1.0.0
        with:
          mongodb-version: 5.0
      - run: curl http://localhost:27017

      
      # npm run start:test
      # npm test -- full tests
      # npm run test:unit         # unit tests only
      # add uses aws ???
      # deploy to s3
